version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: ./nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8000:80"
        links:
            - php-fpm
        user: "${DOCKER_USER:-root}"  

    php-fpm:
        build:
            context: ./docker
            dockerfile: ./php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        user: "${DOCKER_USER:-root}"   

    php-cli:
        build:
            context: ./docker
            dockerfile: ./php-cli.docker
        volumes:
            - ./:/var/www
            - ~/.symfony5:/root/.symfony5 # Монтируем директорию Symfony с хоста
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        user: "${DOCKER_USER:-root}"  
        tty: true        
        entrypoint: >
            sh -c "
            if [ ! -f /usr/local/bin/symfony ]; then
                curl -sS https://get.symfony.com/cli/installer | bash
                mv /root/.symfony5/bin/symfony /usr/local/bin/symfony;
            fi;
            php -a"
    mysql:
        build:
            context: ./docker
            dockerfile: ./mysql.docker
        restart: always
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - 3306:3306
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        expose:
            - 3306
        user: "${DOCKER_USER:-root}"  
